server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/catalogdb
    username: postgres
    password: admin

  datasource:
    url: jdbc:postgresql://postgres:5432/catalogdb
    username: postgres
    password: admin

  flyway:
    enabled: true
