spring:
  application:
    name: catalog-service
  profiles:
    active: local

server:
  port: 8081

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/catalogdb
    username: postgres
    password: admin

  datasource:
    url: jdbc:postgresql://localhost:5433/catalogdb
    username: postgres
    password: admin

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
